# Generated by Django 3.2.9 on 2022-01-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('income', models.FloatField()),
                ('expense', models.FloatField()),
                ('category', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
            ],
        ),
    ]
